language: node_js
node_js:
- lts/*
before_install:
- docker-compose -f docker-compose-local.yml up --build -d
- echo "Testing Docker Hub credentials"
- docker -v
- docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
- echo "Docker Hub credentials are working"
after_success:
- export ACTUAL_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "Test Success - BranchActual($ACTUAL_BRANCH) Pull Request($TRAVIS_PULL_REQUEST)
  Tag($TRAVIS_TAG) PR($TRAVIS_PULL_REQUEST) Build($TRAVIS_BUILD_NUMBER)"
- if [[ "$ACTUAL_BRANCH" == "master" ]]; then echo -e "Push Container to Docker Hub";
  fi
- docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
- export REPO=aista/gmaps-adapter
- export TAG=`if [ "$ACTUAL_BRANCH" == "master" ]; then echo "latest";else echo "";
  fi`
- docker build -f Dockerfile -t $REPO:$TAG .
- docker push $REPO
env:
  global:
  - secure: jdSMPVie2n1oailU8yaeI21euX3PSBd3I5Fsz9f+u+JhKDEoMSHy1R/ml8t1MCNEiQgdAl/rODHR5W95j+ZcpA97NzpeOMqteaPsqEJF0fWEueBsKBoaJsMwNfUSz74BN8K2dZD3KqDrXptoDch9uYgDioVlhSCpznWLZ5enDdMjblV/6WN0rj+HjV5j04APpBNWN8KoghG/rPfOukt0C4UlN4CglLViSazNSlIM6IMJ+W3s4V5J+LZ6g/msez1rPZPSTGx3h0Sy3lh0Ezo9S08jY8VLY8Pp1+dLwgFQq/JTB7vIYrjIzj0Ka8nMtDUN2jgqkSzNHJSD796wromdSpJejx/LopCEfckRYT6uvCmqm7Lyo3UC7OL0p5UwV0VM8AGk0mStVFtj58Byg5GPZrXAPuo4zYckOqsWgCJsY+GEIl2KyBWBCbgvRAVf0yLie1TOKJf9UVRL++sgdq3Jjy47AG01GVccFFHf0+LV0AJlU/WK+40uGhbAvVAwjFyvBX2+0UPloC7LjDvKxI0KpmJv9gKxSHUQTZNEQIblvFgjemOHnm1D/wooNukZ2ufvhvZIUO+7F7sWSD2OzOOa7Iuu/f3CTePtPeuXRUuz4595Dlo7FapOdhOcMomHnHouTVpeA2GQvRASQ1+40CX31zj5YrQepOlv2oMY9BC79gg=
  - secure: djfLxKG1bzBfJhXw+qC5E13x1VNBLbYUqTvRKymGVN9mAk28WyUH/WphA+ZY7TcI6OPiZQQ6RO0jpCggRLfsdch8370NBm12QLeJcZCyRpIf5aVIcbkuHI9nyzWvzNyjR0pfG5m3z9Hhq0WxzMAaPQgLsiAc5IrDHauBPbDJmBgkAv30pJSBGPAQBqVbTnPyp9ZUDCkbNeWMsh1JwWsVHKiyVhpAof8nT96j4H1wh9YfRT8hZdMZletdNz0jIYiTZUaeAtz7pvkk153rGHIN6HUZJh+wbWkQOfeZVlltS0rNpr+Wo0XBuqrNNZOoNxCBH9oSzIIcQUWPxUiGgkStnYBLfbZWxlaLCYMuOlonTM0HMxPWsAwIjUXf6N0LykKkMqRwZwp8UyEQjOQjDtoT6f02VGgt3+DIrE+bua01wHrKlCxQ/Vdn99K7B30ocsSyGl81OLYetytm0Kg0MV5ip1ulffaEcqK3yTqMiq3IWZ5sMfypd8LZEJn5I5afNsn8JKHqJ9cC9d4nD2V9HZ4gP1+IDx/q5Qx409GSdDKMQtC3bVNDa/N6hjDZ2pkoA3gWtRaOpX4+HoExrTirhLfpSiSEg7zPTEKxqJXFcCxom+HdFg6lNGHNichNfGr/ZVSeQCn6yKnqf2jenk723HfBGbnTAnr63RQjlPnTL2UIyF4=
notifications:
  slack:
    rooms:
      secure: hmImquTGj4fSfffHVdmc8EpplaCVEghTIys10oOlc5lRiv9p+RVugMR5za/Fu/tQ+B3sAbjtkPRiPKxi1tbDu0hZQpoRn0BS0aR1aEJRVn5HdaXqq06tDcSm/qO2Bq1ANOCsIY3+TvkOLabSs/qCwPnIV73+DzONFv1YUhF73aMCW3PjApik8+wlQ2/EEjML7xi9Z5Uo4h7EpBj2eBIut4JHnKHhy6Gqwa+rl3HAaRaHDmhxNQXYzToT+H54N3mUnnZcO5qwPolXb+YBqybREXIiYShxc/xgCKWFfjj1zZTtoADDrEHDbdZcZbeLveJFM0BBaqGCTZDbLhVckKuJrytsRXdiVUDuwuZ+i5dqERmF4GKdNM8c9wAG4C6PIvE8BPmFrFoe9fHGFfEgAPj+p1dMVq+dZXf9zsZ5Xr0C4+ZH9cswNsHeb1DiOmyTrVWs2HYyAv5vzgIJwCDKkAWpQoqHWPzKBqzG+ZyxfQiEckrACZhKE7dOXphTinYp4Qq6J13AoOJQJFd9k73RTlXsKLEpPGoYC1Bt5et8obTjkVyJ0H/iRVHjfz2F2XOC0eXLttnUfr0TZ8S2oR7B4cKYQ6YtCv72aKo3NJoBcdgDhF0+Je76uBJG+nmgFx/7qaXUQnrWHQROneCkY8DgAejJHR8wiAJhM88fwhLtLXgHnGY=
    on_success: always
    on_failure: always