version: '3'
services:
  discovery-service:
    image: springcloud/eureka
    ports:
      - "8761:8761"


  gmaps-adapter:
    depends_on:
      - discovery-service
    links:
      - discovery-service
    build: ./
    ports:
      - "8080"
    environment:
      - EUREKA_SERVER=discovery-service