version: '3'

services:

  discoveryservice:
    image: springcloud/eureka
    ports:
      - "8761:8761"
  
  gmaps-adapter:
    build: ./
    depends_on:
      - discoveryservice
    links:
      - discoveryservice
    ports:
      - "8080"
    environment:
      - EUREKA_SERVER=discoveryservice