version: '3'
services:
  discoveryservice:
    image: aista/eureka
    ports:
      - "8761:8761"
  gmaps-adapter:
    depends_on:
      - discoveryservice
    build: ./
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER=discoveryservice