version: '2.3'

services:

  discoveryservice:
    image: aista/eureka
    mem_limit: 512M
    ports:
      - "8761:8761"
      
  rabbitmq:
    image: rabbitmq:management
    mem_limit: 512M
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"

  gmaps-adapter:
    build: ./
    mem_limit: 512M
    depends_on:
      - discoveryservice
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER=discoveryservice
      - RABBIT_HOST=rabbitmq